### GET posts/:id
GET http://localhost:4000/api/posts/1

### GET posts
GET http://localhost:4000/api/posts

### POST Creating a new post
POST http://localhost:4000/api/posts
Content-Type: application/json

{
    "title":"Learning vscode",
    "description":"It´s fun",
    "image_url": "https://img.code/34322323.png"
}
